services:
  - type: web
    name: itatiaia-gravador
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        sync: false
      - key: AUDD_API_KEY
        sync: false
